environment: dev

default:
    env: dev
    port: 8080
    jwt_secret: sldgkhoiu58340th0089y
    database_uri: mongodb+srv://user1:Y4yPwn3W6dakmjvq@cluster0.rex5l.mongodb.net/karma
    logging_level: debug
    authentication_timeout: 36000
    portal_cache_timeout: 60
    email:
      title: Test mail from yoga
      to: ssjkamil@gmail.com
    email_server:
      username: example@gmail.com
      password: password
    credentials:
      username: admin
      password: admin



